dofile_once("mods/AdventureMode/lib/coroutines.lua")
dofile_once("data/scripts/lib/utilities.lua")
dofile_once("mods/AdventureMode/files/camera.lua")
dofile_once("mods/AdventureMode/files/util.lua")

local entity_id = GetUpdatedEntityID()
local x, y = EntityGetTransform(entity_id)

local players = EntityGetWithTag("player_unit")
if #players > 0 then
  local player = players[1]
  local cx, cy = camera_get_position()
  local this_component = GetUpdatedComponentID()
  async(function()
    set_controls_enabled(false)
    set_camera_manual(true)
    camera_tracking_shot(cx, cy, x, y, 0.01)
    local chest = EntityLoad("mods/AdventureMode/files/chest.xml", x, y + 1)
    set_var_store_string(chest, "item_to_drop", "mods/AdventureMode/files/torch.xml")
    wait_until(function()
      return get_var_store_bool(chest, "is_done")
    end)
    wait(30)
    camera_tracking_shot(x, y, cx, cy, 0.01)
    camera_set_position(cx, cy)
    set_camera_manual(false)
    set_controls_enabled(true)
    EntityKill(entity_id)
  end)
end
